name: Generate PKG Info

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest Mihomo release info
        run: |
          # Clone repo dan ambil commit terbaru dari branch main
          git clone --depth=1 https://github.com/MetaCubeX/mihomo.git
          cd mihomo

          # Ambil informasi commit
          COMMIT=$(git rev-parse HEAD)
          DATE=$(git log -1 --format=%cd --date=format:'%Y-%m-%d')
          VERSION=alpha-${COMMIT:0:8}

          # Arsipkan dan kompres
          cd ..
          mv mihomo mihomo-${DATE}~${COMMIT:0:8}
          tar -caf mihomo-${DATE}~${COMMIT:0:8}.tar.zst mihomo-${DATE}~${COMMIT:0:8}

          # Hitung hash
          HASH=$(sha256sum mihomo-${DATE}~${COMMIT:0:8}.tar.zst | cut -d ' ' -f1)

          # Output hasil
          echo "PKG_SOURCE_DATE=$DATE" >> $GITHUB_ENV
          echo "PKG_SOURCE_VERSION=$COMMIT" >> $GITHUB_ENV
          echo "PKG_BUILD_VERSION=$VERSION" >> $GITHUB_ENV
          echo "PKG_MIRROR_HASH=$HASH" >> $GITHUB_ENV

      - name: Print results
        run: |
          echo "PKG_SOURCE_DATE=$PKG_SOURCE_DATE"
          echo "PKG_SOURCE_VERSION=$PKG_SOURCE_VERSION"
          echo "PKG_BUILD_VERSION=$PKG_BUILD_VERSION"
          echo "PKG_MIRROR_HASH=$PKG_MIRROR_HASH"
